FROM ubuntu:18.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  bash-completion \
  git \
  locales \
  man \
  netcat-traditional

RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
   && locale-gen en_US.utf8 \
   && /usr/sbin/update-locale LANG=en_US.UTF-8

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  python3 \
  python3-pip \
  libpq-dev

RUN pip3 install pandas numpy
RUN pip3 install flask psycopg2 schema enum34 xlrd blinker
